---
abstract: 'Simple text template engine'
author:
  - 'Burak Gursoy <burak@cpan.org>'
build_requires:
  File::Temp: 0.12
  Test::More: 0.40
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Template-Simple
no_index:
  directory:
    - monolithic_version
    - builder
    - t
provides:
  Text::Template::Simple:
    file: lib/Text/Template/Simple.pm
    version: 0.82
  Text::Template::Simple::Base::Compiler:
    file: lib/Text/Template/Simple/Base/Compiler.pm
    version: 0.82
  Text::Template::Simple::Base::Examine:
    file: lib/Text/Template/Simple/Base/Examine.pm
    version: 0.82
  Text::Template::Simple::Base::Include:
    file: lib/Text/Template/Simple/Base/Include.pm
    version: 0.82
  Text::Template::Simple::Base::Parser:
    file: lib/Text/Template/Simple/Base/Parser.pm
    version: 0.82
  Text::Template::Simple::Cache:
    file: lib/Text/Template/Simple/Cache.pm
    version: 0.82
  Text::Template::Simple::Cache::ID:
    file: lib/Text/Template/Simple/Cache/ID.pm
    version: 0.82
  Text::Template::Simple::Caller:
    file: lib/Text/Template/Simple/Caller.pm
    version: 0.82
  Text::Template::Simple::Compiler:
    file: lib/Text/Template/Simple/Compiler.pm
    version: 0.82
  Text::Template::Simple::Compiler::Safe:
    file: lib/Text/Template/Simple/Compiler/Safe.pm
    version: 0.82
  Text::Template::Simple::Constants:
    file: lib/Text/Template/Simple/Constants.pm
    version: 0.82
  Text::Template::Simple::Dummy:
    file: lib/Text/Template/Simple/Dummy.pm
    version: 0.82
  Text::Template::Simple::IO:
    file: lib/Text/Template/Simple/IO.pm
    version: 0.82
  Text::Template::Simple::Tokenizer:
    file: lib/Text/Template/Simple/Tokenizer.pm
    version: 0.82
  Text::Template::Simple::Util:
    file: lib/Text/Template/Simple/Util.pm
    version: 0.82
recommends:
  Devel::Size: 0.72
  Perl::Tidy: 0
  Text::Table: 1.107
requires:
  Digest::MD5: 1.00
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-text-template-simple/
version: 0.82
