---
name: Text-Template-Simple
version: 0.49_08
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Simple text template engine
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Dumper: 2.101
  Fcntl: 1.03
  File::Find: 0
  File::Spec: 0.6
  IO::File: 1.06021
  IO::Handle: 1.1505
  Safe: 2.06
  Test::More: 0.40
recommends:
  Devel::Size: 0.64
  Text::Table: 1.107
provides:
  Text::Template::Simple:
    file: lib/Text/Template/Simple.pm
    version: 0.49_08
  Text::Template::Simple::Caller:
    file: lib/Text/Template/Simple/Caller.pm
    version: 0.10
  Text::Template::Simple::Compiler:
    file: lib/Text/Template/Simple/Compiler.pm
    version: 0.10
  Text::Template::Simple::Compiler::Safe:
    file: lib/Text/Template/Simple/Compiler/Safe.pm
    version: 0.10
  Text::Template::Simple::Constants:
    file: lib/Text/Template/Simple/Constants.pm
    version: 0.10
  Text::Template::Simple::Dummy:
    file: lib/Text/Template/Simple/Dummy.pm
    version: 0.10
  Text::Template::Simple::Tokenizer:
    file: lib/Text/Template/Simple/Tokenizer.pm
    version: 0.10
  Text::Template::Simple::Util:
    file: lib/Text/Template/Simple/Util.pm
    version: 0.10
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
