---
name: Text-Template-Simple
version: 0.2
author:
  - Burak Gursoy <burak@cpan.org>
abstract: A simple template class mainly for web applications.
license: perl
requires:
  Text::Template: 1.44
provides:
  Text::Template::Simple:
    file: lib/Text/Template/Simple.pm
    version: 0.2
  Text::Template::Simple::Dummy:
    file: lib/Text/Template/Simple.pm
    version: 0.2
  Text::Template::Simple::Sub:
    file: lib/Text/Template/Simple.pm
    version: 0.2
generated_by: Module::Build version 0.2611
