---
name: Text-Template-Simple
version: 0.49_06
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Simple text template engine
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Dumper: 2.101
  Fcntl: 1.03
  File::Find: 0
  File::Spec: 0.6
  IO::File: 1.06021
  IO::Handle: 1.1505
  Safe: 2.06
  Test::More: 0.40
recommends:
  Devel::Size: 0.64
  Text::Table: 1.107
provides:
  Text::Template::Simple:
    file: lib/Text/Template/Simple.pm
    version: 0.49_06
  Text::Template::Simple::Caller:
    file: lib/Text/Template/Simple.pm
  Text::Template::Simple::Compiler:
    file: lib/Text/Template/Simple.pm
  Text::Template::Simple::Compiler::Safe:
    file: lib/Text/Template/Simple.pm
  Text::Template::Simple::Dummy:
    file: lib/Text/Template/Simple.pm
  Text::Template::Simple::Tokenizer:
    file: lib/Text/Template/Simple.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
