#!/usr/bin/perl -w
use strict;
use vars qw( %PREREQ %RECOMMEND $AUTHOR $MODULE );

$AUTHOR = 'Burak Gursoy <burak@cpan.org>';
$MODULE = 'Text::Template::Simple';

%PREREQ = (
    # ActiveState's build system seem to have issues with dual life ones
    # that's really dumb though...
    #'Data::Dumper' => '2.101',
    #'Safe'         => '2.10',
    #'File::Spec'   => '0.6',
    #'File::Find'   => '0',
    #'IO::Handle'   => '1.1505',
    #'IO::File'     => '1.06021',
    #'Fcntl'        => '1.03',
    'File::Temp'   => '0.12',
    'Digest::MD5'  => '1.00',
    'Test::More'   => '0.40',
);

%RECOMMEND = (
    'Devel::Size'  => '0.64',
    'Text::Table'  => '1.107',
    'Perl::Tidy'   => '0',
);

1;
